spring:
  datasource:
    name: hhsqlog  #数据库名
    url: jdbc:mysql://localhost:3306/hhsqlog #url
    username: root
    password: Zwfwz@52525
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
  resources:
    static-locations: classpath:templates/,classpath:static/,classpath:node_modules/
  mvc:
    view:
#      prefix: html/
      suffix: .html
mybatis:
  mapper-locations: classpath:generator/*.xml